"""add note

Revision ID: 7f28531e7368
Revises: b5ed0a8a8407
Create Date: 2022-12-19 22:39:33.714723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f28531e7368'
down_revision = 'b5ed0a8a8407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('note', sa.String(length=1500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'note')
    # ### end Alembic commands ###
