"""item updates

Revision ID: 9d3ab3248ef6
Revises: 7f058197e57c
Create Date: 2023-06-30 14:25:40.360434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3ab3248ef6'
down_revision = '7f058197e57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('item', sa.Column('abbreviation', sa.String(length=32), nullable=True))
    op.add_column('item', sa.Column('itemtype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'item_type', ['itemtype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'itemtype_id')
    op.drop_column('item', 'abbreviation')
    op.drop_table('item_type')
    # ### end Alembic commands ###
