"""item abbreviations

Revision ID: cb35734e69b0
Revises: 7f058197e57c
Create Date: 2023-06-29 16:05:53.355788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb35734e69b0'
down_revision = '7f058197e57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('abbreviation', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'item', ['abbreviation'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_column('item', 'abbreviation')
    # ### end Alembic commands ###
