"""item updates

Revision ID: e3ee326f96b8
Revises: 7f058197e57c
Create Date: 2023-06-30 13:09:16.834289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ee326f96b8'
down_revision = '7f058197e57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('abbreviation', sa.String(length=32), nullable=True))
    op.add_column('item', sa.Column('itemtype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'item_type', ['itemtype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'itemtype_id')
    op.drop_column('item', 'abbreviation')
    # ### end Alembic commands ###
